language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: build/libs/*
  draft: true
  on:
    repo: colin-bz/labpipe-server-public