language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy: "cd $HOME/build/libs && ls"
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  file: "$HOME/build/libs/labpipe-server-kotlin-*-all.jar"
  draft: true
  on:
    repo: colin-bz/labpipe-server-public