name: Gradle Release

on: [create]
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Show tag
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: |
        ./gradlew build
        curl --data $'{"tag_name":"${{github.event.ref}}","target_commitish": "master","name": "${{github.event.ref}}","body": "Release ${{github.event.ref}}","draft": true,"prerelease": false}' https://api.github.com/repos/$GITHUB_REPOSITORY/releases\?access_token=$GITHUB_TOKEN
        RELEASE_ID=$(curl https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{github.event.ref}}?access_token=$GITHUB_TOKEN | jq '.id')
        for filename in $PWD/build/libs; do curl --data-binary @"$PWD/build/libs/$filename" -H "Content-Type: application/java-archive" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/${{github.event.ref}}/assets?name=$(basename $filename) ; done
